name: Performance Benchmarks
permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  benchmark:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Install dependencies
        run: npm ci

      - name: Build Libs
        run: npm run build:libs

      - name: Run Benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: npm run bench
        env:
          CODSPEED_FORCE_OPTIMIZATION: true
